import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/header/Header";

export const metadata: Metadata = {
  title: "HW Tour - Đặt Tour du lịch tiện lợi và nhanh chóng",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Header />
        
        {children}
        
        </body>
    </html>
  );
}
