import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/header/Header";
import { Footer } from "@/components/footer/Footer";
import { BoxContact } from "@/components/box-contact/BoxContact";
import { ButtonBackToTop } from "@/components/button/ButtonBackToTop";
import { QueryProvider } from "@/providers/QueryProvider";

export const metadata: Metadata = {
  title: "36.Travel - Đặt Tour du lịch tiện lợi và nhanh chóng",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <QueryProvider>
          <Header />
          {children}
          <Footer />
          <BoxContact />
          <ButtonBackToTop />
        </QueryProvider>
      </body>
    </html>
  );
}
